### ISSUE TITLE
White screen is happening for logged-out users when the plugin is active with no constant

### ISSUE THREAD

**Issue by Benunc** [Shelob9/headless-mode#16]
Steps to replicate: 

1. Install and activate plugin.
2. Visit the site in a logged out browser.
3. Whitescreen.

Here's a video: https://screencast-o-matic.com/watch/cre1rmVchyC

**Comment by Shelob9** [comment]
Ok, but what should it do?

**Comment by majoravery** [comment]
Hi @Benunc , how did you undo the white screen even when visiting the /wp-admin page to login? 

I did a silly and put the same URL as my WP backend into the `HEADLESS_MODE_CLIENT_URL` variable and now I can't log in. I've disabled all the WP plugins via phpMyAdmin and I'm hoping it'll restore the page/remove the redirects but it's been almost 2 hours and I'm not sure if I'm still as hopeful. Any advice appreciated! 🙏🏻
