### ISSUE TITLE
Is it compatible for wordpress 6.3.2 version?

### ISSUE THREAD

**Issue by alperenmehmet** [Shelob9/headless-mode#22]
I am using the "Headless Mode" plugin on my WordPress site and I am currently running version 6.3.2. I am interested in knowing if this plugin is compatible with this version of WordPress.

I added, 
```
define( 'HEADLESS_MODE_CLIENT_URL', 'https://example.com/wp-login.php' )
``` 
in wp-config.php file. But it's not working. It gives me HTTP ERROR 500.

**Comment by Shelob9** [comment]
Should work. Sounds like you have a PHP error.
